In [7]:
import tensorflow as tf

a = tf.placeholder(dtype=tf.int32, name = 'a')
b = tf.constant(1,name= 'b')
c = a+b

with tf.Session() as sess:
    print('a+b=',sess.run(c,feed_dict={a:8}))
    

a+b= 9


In [10]:
a = tf.constant(2,name='a')
b = tf.constant(3,name='b')
c = tf.add(a,b)
d = tf.multiply(a,b)
with tf.Session() as sess:
    print('a+b=',sess.run(c))
    print('a*b=',sess.run(d))
    

a+b= 5
a*b= 6


In [23]:
a = tf.constant([[1,2,4],[5,7,6]],name = 'a')
b = tf.constant([[1,5,3],[2,8,7],[4,7,5]],name='b')
c = tf.matmul(a,b)

print('shape of a:',a.shape)
print('shape of b:',b.shape)
print('shape of c:',c.shape)

with tf.Session() as sess:
    print('a=\n',sess.run(a))
    print('b=\n',sess.run(b))
    print('c=\n',sess.run(c))
    


shape of a: (2, 3)
shape of b: (3, 3)
shape of c: (2, 3)
a=
 [[1 2 4]
 [5 7 6]]
b=
 [[1 5 3]
 [2 8 7]
 [4 7 5]]
c=
 [[ 21  49  37]
 [ 43 123  94]]


In [18]:
a = tf.constant([1,2,3],name='a')
b = tf.constant([4,5,6],name='b')

c = a+b
with tf.Session() as sess:
    print('a+b = ',sess.run(c))

a+b =  [5 7 9]
